version: '3.8'

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/code/
      - static_volume:/code/staticfiles/
    ports:
      - "8000:8000"
      - "3000:3000"
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=android_user
      - POSTGRES_PASSWORD=4ndr0id!@
      - POSTGRES_DB=android_db
    ports:
      - "5432:5432"
volumes:
  static_volume:
  postgres_data: