version: '3.8'

services:
  web:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile.local
    command: python manage.py robel_dbunserver 0.0.0.0:8000
    volumes:
      - static_volume:/code/staticfiles/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=android_user
      - POSTGRES_PASSWORD=4ndr0id!@
      - POSTGRES_DB=android_db
    ports:
      - "15432:5432"
volumes:
  static_volume:
  postgres_data: